### PR TITLE
Add Webhook alerting functionality

### PR DESCRIPTION
**Pull request by npmaile**
addressing issue #50 
This pull request adds a webhook dispatcher client to the client library. 
At the time of writing this, it is a draft to ensure the code style I've written is compatible with the standards of the project. 
Please let me know if anything needs changing while I write tests and example code.

### CODE REVIEW

**Comment by vaibhav-kaushal** [comment]
@npmaile That's not what was was needed! You can see that the AlertWebhook type was left as `// AlertWebhook webhook` and the type was defined as `// type webhook func(models.BarkLog) error` (both were commented)!

The webhook was supposed to be used as a mere function - this is a function that was to be supplied by the user. We have to understand the usage of the webhook. The usage ties to the `ALERT` log level. So that when the client (and maybe someday the server too) encounters an `ALERT` level log, it will call the supplied webhook function. The function of this Webhook is to call an external service, primarily for _alerting_ the user of a near-fatal event, something that needs to be looked into urgently.

Now, different people have different needs. My alerting mechanism might be to send the event to slack while another person or team might want to send alert to PagerDuty while someone else might want to trigger am email to their SRE team or whatever. We can't determine what the user will do. 

So the best we can do is to leave the option open - let the user write the function that does what they need. The authentication mechanism, the method to call (HTTP/GRPC/send to another channel etc.) is open to their choices. Hence that choice. That was the reason why such definitions were chosen.

**Comment by npmaile** [comment]
> @npmaile That's not what was was needed! You can see that the AlertWebhook type was left as `// AlertWebhook webhook` and the type was defined as `// type webhook func(models.BarkLog) error` (both were commented)!
> 
> The webhook was supposed to be used as a mere function - this is a function that was to be supplied by the user. We have to understand the usage of the webhook. The usage ties to the `ALERT` log level. So that when the client (and maybe someday the server too) encounters an `ALERT` level log, it will call the supplied webhook function. The function of this Webhook is to call an external service, primarily for _alerting_ the user of a near-fatal event, something that needs to be looked into urgently.
> 
> Now, different people have different needs. My alerting mechanism might be to send the event to slack while another person or team might want to send alert to PagerDuty while someone else might want to trigger am email to their SRE team or whatever. We can't determine what the user will do.
> 
> So the best we can do is to leave the option open - let the user write the function that does what they need. The authentication mechanism, the method to call (HTTP/GRPC/send to another channel etc.) is open to their choices. Hence that choice. That was the reason why such definitions were chosen.

no worries. That's why I only opened the draft and didn't start testing anything yet. It wasn't particularly clear exactly what you wanted from the issue that was open at the time, and I didn't get any guidance when I mentioned it in the Discord. No need to hit me with the two exclamations there.

**Comment by vaibhav-kaushal** [comment]
Cool. Just to say it - I use exclamation ❗ marks rather freely.  ---- On Wed,11 Oct 2023 16:07:51 +0530  ***@***.***  wrote ----

@npmaile That's not what was was needed! You can see that the AlertWebhook type was left as // AlertWebhook webhook and the type was defined as // type webhook func(models.BarkLog) error (both were commented)!
The webhook was supposed to be used as a mere function - this is a function that was to be supplied by the user. We have to understand the usage of the webhook. The usage ties to the ALERT log level. So that when the client (and maybe someday the server too) encounters an ALERT level log, it will call the supplied webhook function. The function of this Webhook is to call an external service, primarily for alerting the user of a near-fatal event, something that needs to be looked into urgently.
Now, different people have different needs. My alerting mechanism might be to send the event to slack while another person or team might want to send alert to PagerDuty while someone else might want to trigger am email to their SRE team or whatever. We can't determine what the user will do.
So the best we can do is to leave the option open - let the user write the function that does what they need. The authentication mechanism, the method to call (HTTP/GRPC/send to another channel etc.) is open to their choices. Hence that choice. That was the reason why such definitions were chosen.

no worries. That's why I only opened the draft and didn't start testing anything yet. It wasn't particularly clear exactly what you wanted from the issue that was open at the time, and I didn't get any guidance when I mentioned it in the Discord. No need to hit me with the two exclamations there.

**Comment by npmaile** [comment]
closing in favor of #68

**Pull request closed without merging**
